### ISSUE TITLE
Create middleware for getting log level as a header

### ISSUE THREAD

**Issue by akeemphilbert** [wepala/weos-controller#15]
## Describe solution or feature request
Similar to how RequestID middleware works - https://echo.labstack.com/middleware/request-id/ create a middleware that will accept the log level as a header and use that to configure the logger for the current request. The log level should be set to the context. The header should be `X-LOG-LEVEL`

values:
1. debug
2. info
3. warn
4. error

## UAT
1. Configure the authentication API to use the weos-controller version on this branch (e.g. go get github.com/wepala/weos-controller@"97ed0f4c3460f6de06bcc3266f580a21def14851")
1. Configure API to use the log level middleware 
1. Set API log level to error by default
1. Setup handler that logs a debug message 
1. Run server go run server.go
1. Confirm only error messages are logged by call endpoint associated with the handler that sends a debug message (the debug message should not be output)
1. Make a request with X-LOG-LEVEL header set to debug 
1. Confirm that the debug message is output

## How does this tie into our current product?
This will allow us to set the log level to error by default and use debug, or info while debugging by setting a header on the request - https://devopedia.org/log-level-per-request

## Who asked for this?
@akeemphilbert 

## Deployment Steps
- [ ] Merge changes into Dev
- [ ] Pull this version of the package into API which it's being used
- [ ] Rebuild the server ( go build <server_name.>go )
- [ ] Run the server ( go run <server_name.>go )
​
## SubTasks
- [x] Write test to simulate a log level being passed in and what output results
- [x] Create a middleware to set Log level for a request
- [x] Ensure middleware accepts log level thru header X-LOG-LEVEL

**Comment by akeemphilbert** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WeOS-611e87f5ac74890014a268df/issues/wepala/weos-controller/15?planning-poker) with ZenHub @RandyDeo @shaniah868

**Comment by akeemphilbert** [comment]
To be clear this is setting the "log level" on the logger based on what is passed in the header

**Comment by akeemphilbert** [comment]
I tried bringing in the updated module (it's been merged to dev), but when I set the header I don't notice a change the header X-LOG-LEVEL to debug I don't notice debug statements coming through
