### ISSUE TITLE
Set GORM log level based on context

### ISSUE THREAD

**Issue by akeemphilbert** [wepala/weos-controller#16]
### Due Date: 01/12/21
​
# Description
<pre>
Use the log level in the context #15 when setting up the GORM logger. 
</pre>
​
# UAT
<pre>
Place UAT here
</pre>
​
# Deployment Steps
- [ ] Merge changes into Dev
- [ ] Pull this version of the package into API which it's being used
- [ ] Rebuild the server ( go build <server_name.>go )
- [ ] Run the server ( go run <server_name.>go )
​
# SubTasks
- [x] Write a test case to check for the log level indicated in the context being that which is in setup gorm logger
- [x] Edit the gorm setup to use log level from context

​

**Comment by akeemphilbert** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WeOS-611e87f5ac74890014a268df/issues/wepala/weos-controller/16?planning-poker) with ZenHub @RandyDeo @shaniah868
