### ISSUE TITLE
Switch to using Zap as the default logger 

### ISSUE THREAD

**Issue by akeemphilbert** [wepala/weos-controller#18]
## Describe solution or feature request
Right now we're just using the echo logger. The zap logger will give more flexibility (logging lines with context is the main improvement). This will lead to setting up a custom error handler and updating the logger middleware as well

## UAT
1. Configure the authentication API to use the weos-controller version on this branch (e.g. `go get github.com/wepala/weos-controller@"97ed0f4c3460f6de06bcc3266f580a21def14851"`)
1. Run server `go run server.go`
1. Confirm that Zep logger is being used (and not the echo logger)

## How does this tie into our current product?
This should improve the performance slightly 

## Who asked for this?
@akeemphilbert 

## Deployment Steps
<pre>
Update build version
Merge to dev
Merge to master
</pre>
​
## SubTasks
- [x] Create tests to test for both context and echo loggers to zap loggers
- [x] Update code on initialize to update echo logger to use zaplogger
- [x] Create a  middleware for context loggers to be changed to zaplogger
- [x] Add Documentations for use

**Comment by akeemphilbert** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WeOS-611e87f5ac74890014a268df/issues/wepala/weos-controller/18?planning-poker) with ZenHub @RandyDeo @shaniah868
