### ISSUE TITLE
Add support for gRPC server

### ISSUE THREAD

**Issue by akeemphilbert** [wepala/weos-controller#39]
### Due Date: 26/11/21

# Description
<pre>
Create an initialize function in a "grpc" package to set up and run the gRPC server. Note this is only to get the server running. It should use the configuration to set up interceptors and handlers. There should be the ability to specify the port. </pre>

# UAT
<pre>
Place UAT here
</pre>

# Deployment Steps
<pre>
Place steps here
</pre>

# SubTasks
- [ ] Write test for grpc init func
- [ ] Create a package in weoscontroller called "grpc"
- [ ] Create an initialize function in there 
- [ ] Create a func to run the server

(this needs to take in a context parameter which will be passed in wherever the initialize func is being called. This is because we are not using echo context for grpc therefore native go. context will be utilized)

**Comment by RandyDeo** [comment]
thinking to have a struct as we did in the auth api for the grpc 

eg.
type WeosGrpc struct {
	pb.UnimplementedWeosGrpcServer
	Application weos.Application
}

func (s *WeosGrpc) Initialize( ctx context.Context, api APIInterface, apiConfig string) context.Context

function call would look like 
var newGRPC &weoscontroller.WeosGrpc{}
context := newGRPC.initialize ( &API{}, "./api.yaml")

**Comment by akeemphilbert** [comment]
Handlers seem to be tightly coupled to the server in grpc
