### ISSUE TITLE
Make it so that the HealthCheck handler returns the version

### ISSUE THREAD

**Issue by akeemphilbert** [wepala/weos-controller#41]
## Describe solution or feature request
Make it so that the health check handler returns the "version" configured in the api.yaml file

## UAT
1. Configure health endpoint to use HealthCheck handler 
2. Confirm that the version returned is the same version in the swagger file 

## How does this tie into our current product?
This is a REST API best practice that makes it easier to know what version of the API is currently in use. This could help with supporting backward compatibility on apis

## Who asked for this?
@akeemphilbert 

## Deployment Steps
- [x] Merge changes into Dev
- [ ] Pull this version of the package into API which it's being used
- [ ] Rebuild the server ( go build <server_name.>go )
- [ ] Run the server ( go run <server_name.>go )
​
## SubTasks
- [x] Add version to AppConfig dtos
- [x] Add a line in initialize function to take the version and store it in config
- [x] Add version output the health handler

**Comment by akeemphilbert** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WeOS-611e87f5ac74890014a268df/issues/wepala/weos-controller/41?planning-poker) with ZenHub @RandyDeo @shaniah868
